// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<GameBoyEmulator>>
abstract class GameBoyEmulator implements RustOpaqueInterface {
  Future<Uint8List> getFrameBuffer();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<GameBoyEmulator> newInstance({required List<int> romBytes}) =>
      RustLib.instance.api.crateApiGameBoyEmulatorNew(romBytes: romBytes);

  Future<void> pressButton({required ButtonType button});

  Future<void> releaseButton({required ButtonType button});

  Future<void> stepFrame();
}

enum ButtonType { a, b, start, select, up, down, left, right }
